version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: avontsoft-postgres
    restart: always
    environment:
      POSTGRES_USER: avont
      POSTGRES_PASSWORD: avont123
      POSTGRES_DB: avontdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: avontsoft-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@avontsoft.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: